name: simple_logger_overlay
description: "A simple, Dart 3+ compatible Flutter logging plugin with an in-app draggable overlay, log levels, and Dio support"
version: 0.0.1
repository: https://github.com/sam829/simple_logger_overlay
homepage: https://github.com/sam829/simple_logger_overlay
documentation: https://github.com/sam829/simple_logger_overlay
issue_tracker: https://github.com/sam829/simple_logger_overlay/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_riverpod: ^2.6.1
  get: ^4.7.2
  path_provider: ^2.1.5
  shake: ^3.0.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
